services:
  ollama:
    image: ollama/ollama:latest
    container_name: apc_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:11434/api/tags >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  web:
    build: .
    container_name: apc_web
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gemma3:1b}
    depends_on:
      - ollama
    ports:
      - "3000:3000"

volumes:
  ollama_models:
